// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: test/nomarshaler.proto

package test

import (
	_ "github.com/billyplus/fastproto/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithMarshalUnmarshalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithMarshalUnmarshalSize) Reset() {
	*x = WithMarshalUnmarshalSize{}
	mi := &file_test_nomarshaler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithMarshalUnmarshalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithMarshalUnmarshalSize) ProtoMessage() {}

func (x *WithMarshalUnmarshalSize) ProtoReflect() protoreflect.Message {
	mi := &file_test_nomarshaler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithMarshalUnmarshalSize.ProtoReflect.Descriptor instead.
func (*WithMarshalUnmarshalSize) Descriptor() ([]byte, []int) {
	return file_test_nomarshaler_proto_rawDescGZIP(), []int{0}
}

func (x *WithMarshalUnmarshalSize) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WithUnmarshal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithUnmarshal) Reset() {
	*x = WithUnmarshal{}
	mi := &file_test_nomarshaler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithUnmarshal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithUnmarshal) ProtoMessage() {}

func (x *WithUnmarshal) ProtoReflect() protoreflect.Message {
	mi := &file_test_nomarshaler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithUnmarshal.ProtoReflect.Descriptor instead.
func (*WithUnmarshal) Descriptor() ([]byte, []int) {
	return file_test_nomarshaler_proto_rawDescGZIP(), []int{1}
}

func (x *WithUnmarshal) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WithUnmarshalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithUnmarshalSize) Reset() {
	*x = WithUnmarshalSize{}
	mi := &file_test_nomarshaler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithUnmarshalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithUnmarshalSize) ProtoMessage() {}

func (x *WithUnmarshalSize) ProtoReflect() protoreflect.Message {
	mi := &file_test_nomarshaler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithUnmarshalSize.ProtoReflect.Descriptor instead.
func (*WithUnmarshalSize) Descriptor() ([]byte, []int) {
	return file_test_nomarshaler_proto_rawDescGZIP(), []int{2}
}

func (x *WithUnmarshalSize) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_test_nomarshaler_proto protoreflect.FileDescriptor

const file_test_nomarshaler_proto_rawDesc = "" +
	"\n" +
	"\x16test/nomarshaler.proto\x12\x04test\x1a\x15options/options.proto\"3\n" +
	"\x1bwith_marshal_unmarshal_size\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id:\x04\x88\xac\x1b\x01\" \n" +
	"\x0ewith_unmarshal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"+\n" +
	"\x13with_unmarshal_size\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id:\x04\xa8\xac\x1b\x01B)\x90\xac\x1b\x01Z#github.com/billyplus/fastproto/testb\x06proto3"

var (
	file_test_nomarshaler_proto_rawDescOnce sync.Once
	file_test_nomarshaler_proto_rawDescData []byte
)

func file_test_nomarshaler_proto_rawDescGZIP() []byte {
	file_test_nomarshaler_proto_rawDescOnce.Do(func() {
		file_test_nomarshaler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_nomarshaler_proto_rawDesc), len(file_test_nomarshaler_proto_rawDesc)))
	})
	return file_test_nomarshaler_proto_rawDescData
}

var file_test_nomarshaler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_nomarshaler_proto_goTypes = []any{
	(*WithMarshalUnmarshalSize)(nil), // 0: test.with_marshal_unmarshal_size
	(*WithUnmarshal)(nil),            // 1: test.with_unmarshal
	(*WithUnmarshalSize)(nil),        // 2: test.with_unmarshal_size
}
var file_test_nomarshaler_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_nomarshaler_proto_init() }
func file_test_nomarshaler_proto_init() {
	if File_test_nomarshaler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_nomarshaler_proto_rawDesc), len(file_test_nomarshaler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_nomarshaler_proto_goTypes,
		DependencyIndexes: file_test_nomarshaler_proto_depIdxs,
		MessageInfos:      file_test_nomarshaler_proto_msgTypes,
	}.Build()
	File_test_nomarshaler_proto = out.File
	file_test_nomarshaler_proto_goTypes = nil
	file_test_nomarshaler_proto_depIdxs = nil
}
