// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: test/oneof.proto

package test

import (
	_ "github.com/billyplus/fastproto/options"
	pb "github.com/billyplus/fastproto/test/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// full proto
type OneOfProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TestOneof:
	//
	//	*OneOfProto_VInt32
	//	*OneOfProto_VInt64
	//	*OneOfProto_VUint32
	//	*OneOfProto_VUint64
	//	*OneOfProto_VString
	//	*OneOfProto_VBytes
	//	*OneOfProto_VBool
	//	*OneOfProto_SInt32
	//	*OneOfProto_SInt64
	//	*OneOfProto_Fixed32
	//	*OneOfProto_Fixed64
	//	*OneOfProto_Sfixed32
	//	*OneOfProto_Sfixed64
	//	*OneOfProto_Float32
	//	*OneOfProto_Float64
	//	*OneOfProto_MActor
	//	*OneOfProto_Outer
	TestOneof     isOneOfProto_TestOneof `protobuf_oneof:"test_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfProto) Reset() {
	*x = OneOfProto{}
	mi := &file_test_oneof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfProto) ProtoMessage() {}

func (x *OneOfProto) ProtoReflect() protoreflect.Message {
	mi := &file_test_oneof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfProto.ProtoReflect.Descriptor instead.
func (*OneOfProto) Descriptor() ([]byte, []int) {
	return file_test_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *OneOfProto) GetTestOneof() isOneOfProto_TestOneof {
	if x != nil {
		return x.TestOneof
	}
	return nil
}

func (x *OneOfProto) GetVInt32() int32 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_VInt32); ok {
			return x.VInt32
		}
	}
	return 0
}

func (x *OneOfProto) GetVInt64() int64 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_VInt64); ok {
			return x.VInt64
		}
	}
	return 0
}

func (x *OneOfProto) GetVUint32() uint32 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_VUint32); ok {
			return x.VUint32
		}
	}
	return 0
}

func (x *OneOfProto) GetVUint64() uint64 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_VUint64); ok {
			return x.VUint64
		}
	}
	return 0
}

func (x *OneOfProto) GetVString() string {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_VString); ok {
			return x.VString
		}
	}
	return ""
}

func (x *OneOfProto) GetVBytes() []byte {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_VBytes); ok {
			return x.VBytes
		}
	}
	return nil
}

func (x *OneOfProto) GetVBool() bool {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_VBool); ok {
			return x.VBool
		}
	}
	return false
}

func (x *OneOfProto) GetSInt32() int32 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_SInt32); ok {
			return x.SInt32
		}
	}
	return 0
}

func (x *OneOfProto) GetSInt64() int64 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_SInt64); ok {
			return x.SInt64
		}
	}
	return 0
}

func (x *OneOfProto) GetFixed32() uint32 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_Fixed32); ok {
			return x.Fixed32
		}
	}
	return 0
}

func (x *OneOfProto) GetFixed64() uint64 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_Fixed64); ok {
			return x.Fixed64
		}
	}
	return 0
}

func (x *OneOfProto) GetSfixed32() int32 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_Sfixed32); ok {
			return x.Sfixed32
		}
	}
	return 0
}

func (x *OneOfProto) GetSfixed64() int64 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_Sfixed64); ok {
			return x.Sfixed64
		}
	}
	return 0
}

func (x *OneOfProto) GetFloat32() float32 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_Float32); ok {
			return x.Float32
		}
	}
	return 0
}

func (x *OneOfProto) GetFloat64() float64 {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_Float64); ok {
			return x.Float64
		}
	}
	return 0
}

func (x *OneOfProto) GetMActor() *OtherMessage {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_MActor); ok {
			return x.MActor
		}
	}
	return nil
}

func (x *OneOfProto) GetOuter() *pb.OuterMsg {
	if x != nil {
		if x, ok := x.TestOneof.(*OneOfProto_Outer); ok {
			return x.Outer
		}
	}
	return nil
}

type isOneOfProto_TestOneof interface {
	isOneOfProto_TestOneof()
}

type OneOfProto_VInt32 struct {
	VInt32 int32 `protobuf:"varint,1,opt,name=v_int32,json=vInt32,proto3,oneof"`
}

type OneOfProto_VInt64 struct {
	VInt64 int64 `protobuf:"varint,2,opt,name=v_int64,json=vInt64,proto3,oneof"`
}

type OneOfProto_VUint32 struct {
	VUint32 uint32 `protobuf:"varint,3,opt,name=v_uint32,json=vUint32,proto3,oneof"`
}

type OneOfProto_VUint64 struct {
	VUint64 uint64 `protobuf:"varint,4,opt,name=v_uint64,json=vUint64,proto3,oneof"`
}

type OneOfProto_VString struct {
	VString string `protobuf:"bytes,5,opt,name=v_string,json=vString,proto3,oneof"`
}

type OneOfProto_VBytes struct {
	VBytes []byte `protobuf:"bytes,23,opt,name=v_bytes,json=vBytes,proto3,oneof"`
}

type OneOfProto_VBool struct {
	VBool bool `protobuf:"varint,6,opt,name=v_bool,json=vBool,proto3,oneof"`
}

type OneOfProto_SInt32 struct {
	SInt32 int32 `protobuf:"zigzag32,7,opt,name=s_int32,json=sInt32,proto3,oneof"`
}

type OneOfProto_SInt64 struct {
	SInt64 int64 `protobuf:"zigzag64,8,opt,name=s_int64,json=sInt64,proto3,oneof"`
}

type OneOfProto_Fixed32 struct {
	Fixed32 uint32 `protobuf:"fixed32,9,opt,name=fixed32,proto3,oneof"`
}

type OneOfProto_Fixed64 struct {
	Fixed64 uint64 `protobuf:"fixed64,10,opt,name=fixed64,proto3,oneof"`
}

type OneOfProto_Sfixed32 struct {
	Sfixed32 int32 `protobuf:"fixed32,11,opt,name=sfixed32,proto3,oneof"`
}

type OneOfProto_Sfixed64 struct {
	Sfixed64 int64 `protobuf:"fixed64,12,opt,name=sfixed64,proto3,oneof"`
}

type OneOfProto_Float32 struct {
	Float32 float32 `protobuf:"fixed32,20,opt,name=float32,proto3,oneof"`
}

type OneOfProto_Float64 struct {
	Float64 float64 `protobuf:"fixed64,21,opt,name=float64,proto3,oneof"`
}

type OneOfProto_MActor struct {
	MActor *OtherMessage `protobuf:"bytes,231,opt,name=m_actor,json=mActor,proto3,oneof"`
}

type OneOfProto_Outer struct {
	Outer *pb.OuterMsg `protobuf:"bytes,281,opt,name=outer,proto3,oneof"`
}

func (*OneOfProto_VInt32) isOneOfProto_TestOneof() {}

func (*OneOfProto_VInt64) isOneOfProto_TestOneof() {}

func (*OneOfProto_VUint32) isOneOfProto_TestOneof() {}

func (*OneOfProto_VUint64) isOneOfProto_TestOneof() {}

func (*OneOfProto_VString) isOneOfProto_TestOneof() {}

func (*OneOfProto_VBytes) isOneOfProto_TestOneof() {}

func (*OneOfProto_VBool) isOneOfProto_TestOneof() {}

func (*OneOfProto_SInt32) isOneOfProto_TestOneof() {}

func (*OneOfProto_SInt64) isOneOfProto_TestOneof() {}

func (*OneOfProto_Fixed32) isOneOfProto_TestOneof() {}

func (*OneOfProto_Fixed64) isOneOfProto_TestOneof() {}

func (*OneOfProto_Sfixed32) isOneOfProto_TestOneof() {}

func (*OneOfProto_Sfixed64) isOneOfProto_TestOneof() {}

func (*OneOfProto_Float32) isOneOfProto_TestOneof() {}

func (*OneOfProto_Float64) isOneOfProto_TestOneof() {}

func (*OneOfProto_MActor) isOneOfProto_TestOneof() {}

func (*OneOfProto_Outer) isOneOfProto_TestOneof() {}

var File_test_oneof_proto protoreflect.FileDescriptor

const file_test_oneof_proto_rawDesc = "" +
	"\n" +
	"\x10test/oneof.proto\x12\x04test\x1a\x10test/outer.proto\x1a\x15options/options.proto\x1a\x0etest/msg.proto\"\x94\x04\n" +
	"\n" +
	"OneOfProto\x12\x19\n" +
	"\av_int32\x18\x01 \x01(\x05H\x00R\x06vInt32\x12\x19\n" +
	"\av_int64\x18\x02 \x01(\x03H\x00R\x06vInt64\x12\x1b\n" +
	"\bv_uint32\x18\x03 \x01(\rH\x00R\avUint32\x12\x1b\n" +
	"\bv_uint64\x18\x04 \x01(\x04H\x00R\avUint64\x12\x1b\n" +
	"\bv_string\x18\x05 \x01(\tH\x00R\avString\x12\x19\n" +
	"\av_bytes\x18\x17 \x01(\fH\x00R\x06vBytes\x12\x17\n" +
	"\x06v_bool\x18\x06 \x01(\bH\x00R\x05vBool\x12\x19\n" +
	"\as_int32\x18\a \x01(\x11H\x00R\x06sInt32\x12\x19\n" +
	"\as_int64\x18\b \x01(\x12H\x00R\x06sInt64\x12\x1a\n" +
	"\afixed32\x18\t \x01(\aH\x00R\afixed32\x12\x1a\n" +
	"\afixed64\x18\n" +
	" \x01(\x06H\x00R\afixed64\x12\x1c\n" +
	"\bsfixed32\x18\v \x01(\x0fH\x00R\bsfixed32\x12\x1c\n" +
	"\bsfixed64\x18\f \x01(\x10H\x00R\bsfixed64\x12\x1a\n" +
	"\afloat32\x18\x14 \x01(\x02H\x00R\afloat32\x12\x1a\n" +
	"\afloat64\x18\x15 \x01(\x01H\x00R\afloat64\x12.\n" +
	"\am_actor\x18\xe7\x01 \x01(\v2\x12.test.OtherMessageH\x00R\x06mActor\x12%\n" +
	"\x05outer\x18\x99\x02 \x01(\v2\f.pb.OuterMsgH\x00R\x05outerB\f\n" +
	"\n" +
	"test_oneofB)\xb0\xac\x1b\x01Z#github.com/billyplus/fastproto/testb\x06proto3"

var (
	file_test_oneof_proto_rawDescOnce sync.Once
	file_test_oneof_proto_rawDescData []byte
)

func file_test_oneof_proto_rawDescGZIP() []byte {
	file_test_oneof_proto_rawDescOnce.Do(func() {
		file_test_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_oneof_proto_rawDesc), len(file_test_oneof_proto_rawDesc)))
	})
	return file_test_oneof_proto_rawDescData
}

var file_test_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_oneof_proto_goTypes = []any{
	(*OneOfProto)(nil),   // 0: test.OneOfProto
	(*OtherMessage)(nil), // 1: test.OtherMessage
	(*pb.OuterMsg)(nil),  // 2: pb.OuterMsg
}
var file_test_oneof_proto_depIdxs = []int32{
	1, // 0: test.OneOfProto.m_actor:type_name -> test.OtherMessage
	2, // 1: test.OneOfProto.outer:type_name -> pb.OuterMsg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_oneof_proto_init() }
func file_test_oneof_proto_init() {
	if File_test_oneof_proto != nil {
		return
	}
	file_test_msg_proto_init()
	file_test_oneof_proto_msgTypes[0].OneofWrappers = []any{
		(*OneOfProto_VInt32)(nil),
		(*OneOfProto_VInt64)(nil),
		(*OneOfProto_VUint32)(nil),
		(*OneOfProto_VUint64)(nil),
		(*OneOfProto_VString)(nil),
		(*OneOfProto_VBytes)(nil),
		(*OneOfProto_VBool)(nil),
		(*OneOfProto_SInt32)(nil),
		(*OneOfProto_SInt64)(nil),
		(*OneOfProto_Fixed32)(nil),
		(*OneOfProto_Fixed64)(nil),
		(*OneOfProto_Sfixed32)(nil),
		(*OneOfProto_Sfixed64)(nil),
		(*OneOfProto_Float32)(nil),
		(*OneOfProto_Float64)(nil),
		(*OneOfProto_MActor)(nil),
		(*OneOfProto_Outer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_oneof_proto_rawDesc), len(file_test_oneof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_oneof_proto_goTypes,
		DependencyIndexes: file_test_oneof_proto_depIdxs,
		MessageInfos:      file_test_oneof_proto_msgTypes,
	}.Build()
	File_test_oneof_proto = out.File
	file_test_oneof_proto_goTypes = nil
	file_test_oneof_proto_depIdxs = nil
}
