// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: test/nofast.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoFastMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	Eid int64 `protobuf:"varint,1,opt,name=eid,proto3" json:"eid,omitempty"`
	//
	OpenId string `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	//
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// job
	Job int32 `protobuf:"varint,4,opt,name=job,proto3" json:"job,omitempty"`
	// sex
	Sex         int32                  `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	LastUpdated *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (x *NoFastMessage) Reset() {
	*x = NoFastMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_nofast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoFastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoFastMessage) ProtoMessage() {}

func (x *NoFastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_nofast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoFastMessage.ProtoReflect.Descriptor instead.
func (*NoFastMessage) Descriptor() ([]byte, []int) {
	return file_test_nofast_proto_rawDescGZIP(), []int{0}
}

func (x *NoFastMessage) GetEid() int64 {
	if x != nil {
		return x.Eid
	}
	return 0
}

func (x *NoFastMessage) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *NoFastMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NoFastMessage) GetJob() int32 {
	if x != nil {
		return x.Job
	}
	return 0
}

func (x *NoFastMessage) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *NoFastMessage) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_test_nofast_proto protoreflect.FileDescriptor

var file_test_nofast_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x6e, 0x6f, 0x66, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x0d, 0x4e, 0x6f, 0x46,
	0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x6f, 0x62,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x3d, 0x0a,
	0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x28, 0x5a, 0x26,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x79,
	0x70, 0x6c, 0x75, 0x73, 0x2f, 0x66, 0x61, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_nofast_proto_rawDescOnce sync.Once
	file_test_nofast_proto_rawDescData = file_test_nofast_proto_rawDesc
)

func file_test_nofast_proto_rawDescGZIP() []byte {
	file_test_nofast_proto_rawDescOnce.Do(func() {
		file_test_nofast_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_nofast_proto_rawDescData)
	})
	return file_test_nofast_proto_rawDescData
}

var file_test_nofast_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_nofast_proto_goTypes = []interface{}{
	(*NoFastMessage)(nil),         // 0: pb.NoFastMessage
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_test_nofast_proto_depIdxs = []int32{
	1, // 0: pb.NoFastMessage.last_updated:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_test_nofast_proto_init() }
func file_test_nofast_proto_init() {
	if File_test_nofast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_nofast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoFastMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_nofast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_nofast_proto_goTypes,
		DependencyIndexes: file_test_nofast_proto_depIdxs,
		MessageInfos:      file_test_nofast_proto_msgTypes,
	}.Build()
	File_test_nofast_proto = out.File
	file_test_nofast_proto_rawDesc = nil
	file_test_nofast_proto_goTypes = nil
	file_test_nofast_proto_depIdxs = nil
}
