// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: test/nofast.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoFastMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Eid int64 `protobuf:"varint,1,opt,name=eid,proto3" json:"eid,omitempty"`
	OpenId string `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// job
	Job int32 `protobuf:"varint,4,opt,name=job,proto3" json:"job,omitempty"`
	// sex
	Sex           int32                  `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoFastMessage) Reset() {
	*x = NoFastMessage{}
	mi := &file_test_nofast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoFastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoFastMessage) ProtoMessage() {}

func (x *NoFastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_nofast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoFastMessage.ProtoReflect.Descriptor instead.
func (*NoFastMessage) Descriptor() ([]byte, []int) {
	return file_test_nofast_proto_rawDescGZIP(), []int{0}
}

func (x *NoFastMessage) GetEid() int64 {
	if x != nil {
		return x.Eid
	}
	return 0
}

func (x *NoFastMessage) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *NoFastMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NoFastMessage) GetJob() int32 {
	if x != nil {
		return x.Job
	}
	return 0
}

func (x *NoFastMessage) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *NoFastMessage) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_test_nofast_proto protoreflect.FileDescriptor

const file_test_nofast_proto_rawDesc = "" +
	"\n" +
	"\x11test/nofast.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n" +
	"\rNoFastMessage\x12\x10\n" +
	"\x03eid\x18\x01 \x01(\x03R\x03eid\x12\x17\n" +
	"\aopen_id\x18\x02 \x01(\tR\x06openId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03job\x18\x04 \x01(\x05R\x03job\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\x05R\x03sex\x12=\n" +
	"\flast_updated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdatedB(Z&github.com/billyplus/fastproto/test/pbb\x06proto3"

var (
	file_test_nofast_proto_rawDescOnce sync.Once
	file_test_nofast_proto_rawDescData []byte
)

func file_test_nofast_proto_rawDescGZIP() []byte {
	file_test_nofast_proto_rawDescOnce.Do(func() {
		file_test_nofast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_nofast_proto_rawDesc), len(file_test_nofast_proto_rawDesc)))
	})
	return file_test_nofast_proto_rawDescData
}

var file_test_nofast_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_nofast_proto_goTypes = []any{
	(*NoFastMessage)(nil),         // 0: pb.NoFastMessage
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_test_nofast_proto_depIdxs = []int32{
	1, // 0: pb.NoFastMessage.last_updated:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_test_nofast_proto_init() }
func file_test_nofast_proto_init() {
	if File_test_nofast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_nofast_proto_rawDesc), len(file_test_nofast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_nofast_proto_goTypes,
		DependencyIndexes: file_test_nofast_proto_depIdxs,
		MessageInfos:      file_test_nofast_proto_msgTypes,
	}.Build()
	File_test_nofast_proto = out.File
	file_test_nofast_proto_goTypes = nil
	file_test_nofast_proto_depIdxs = nil
}
